version: '3'
services:
  fsa_level99:
    build:
      context: .
    working_dir: /home/pwn
    container_name: fsa_level99
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9005:9000"
    entrypoint: /etc/init.sh
